### PR TITLE
Add CONTRIBUTE.md

### PR DESCRIPTION
**Pull request by mkuzak**
I think there should be a contribute description. Please consider

### CODE REVIEW

**Comment by c-martinez** [comment]
Good idea baldy, but I should perhaps also have a license file.

**Comment by c-martinez** [comment]
@mkuzak -- License = apache ?

**Comment by mkuzak** [comment]
hell yeah :)
by the way there is template for CONTRIBUTING.md in [exemplum repository](https://github.com/NLeSC/exemplum/blob/master/CONTRIBUTING.md)

**Comment by c-martinez** [comment]
Ok -- I think we had an issue #5  about license conflicts with a dependency. I'll look into it again.

**Pull request merged**
